### PR TITLE
Add nullability and generic annotations to FBFetchedResultsController.h

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Thanks for making this! Core data is broke as hell!

EDIT: note that this only works on Xcode 7

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
Any chance this could get some love now that Xcode 7 is out?

**Comment by adamjernst** [comment]
Sure let me try to prod Travis...

**Comment by adamjernst** [comment]
Sorry @Adlai-Holler, it looks like the Travis build isn't passing. Can you investigate?

**Comment by adamjernst** [comment]
Reopen the PR when you've got it fixed

**Pull request closed without merging**
